export const indianStates = [
  "Andhra pradesh",
  "Arunachal pradesh",
  "Assam",
  "Bihar",
  "Chattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil nadu",
  "Telangana",
  "Tripura",
  "Uttar pradesh",
  "Uttarakhand",
  "West bengal",
  "Andaman & nicobar islands",
  "Chandigarh",
  "Daman & diu",
  "Delhi",
  "Jammu & kashmir",
  "Ladakh",
  "Lakshadweep",
  "Pondicherry",
];